name: Build

on:
  # pull_request:
  #   paths-ignore:
  #     - "cmds/proxy/**"
  #     - "**.md"
  #     - ".github/workflows/on_push_proxy.yaml"
  push:
    paths-ignore:
      - "cmds/proxy/**"
      - "**.md"
      - ".github/workflows/on_push_proxy.yaml"
  # create: # New tag (or branch)
  #   paths-ignore:
  #     - "cmds/proxy/**"
  #     - "**.md"
  #     - ".github/workflows/on_push_proxy.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  empirica:
    name: Build and upload cli
    runs-on: ubuntu-latest
    if: github.repository == 'empiricaly/empirica' && github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4
      - name: Set GITHUB_ENV
        run: |
          echo "BUILD_TAG=${{ steps.branch-name.outputs.tag }}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_SHA=$(git rev-list -1 HEAD)" >> $GITHUB_ENV
          echo "BUILD_SHA_SHORT=$(git rev-parse --short=7 ${{ github.sha }})" >> $GITHUB_ENV
          echo "BUILD_NUM=${{ github.run_number }}" >> $GITHUB_ENV
      # If it's a tag, we assume the branch is main
      - name: Check if running on a tag branch.
        if: steps.branch-name.outputs.is_tag == 'true'
        run: |
          echo "BUILD_BRANCH=`echo "main" | sed -r 's,/,-,g'`" >> $GITHUB_ENV
      # Otherwise use the actual branch name
      - name: Use actual branch name.
        if: steps.branch-name.outputs.is_tag != 'true'
        run: |
          echo "BUILD_BRANCH=`echo "${{ steps.branch-name.outputs.current_branch }}" | sed -r 's,/,-,g'`" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: empirica-tmp
          file: ./build/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_SHA=${{ env.BUILD_SHA_SHORT }}
            BUILD_NUM=${{ env.BUILD_NUM }}
            BUILD_BRANCH=${{ env.BUILD_BRANCH }}
            BUILD_TAG=${{ env.BUILD_TAG }}
      - name: Copy binaries from image
        run: |
          mkdir out
          docker run --rm empirica-tmp tar -cC /out . | tar -xC $(pwd)/out
      - name: Smoke test
        run: ./out/empirica-linux-amd64 --help
      - name: Upload binaries to S3
        uses: ./.github/actions/upload-empirica-cli
        with:
          # NOTE Bucket name might not correspond to final domain name
          bucket: get.empirica.dev
          root: empirica
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./build/Dockerfile.empirica
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_SHA_SHORT }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUM }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_BRANCH }}
